### PR TITLE
Server-side support

### PR DESCRIPTION
**Pull request by gdub22**
- All code can now be safely executed on the server
- The `exec` method now takes an optional `path` parameter which can be used on the server.  This allows the server to use your route handling logic to control what's rendered.

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
cool! @gdub22 thanks!
@cognitom I will let you merge and QA the pull requests on the `riot-route` repo is it ok?

**Comment by cognitom** [comment]
@GianlucaGuarini sure. Will do.

@gdub22 Thanks! I'm bit busy now, I'll check it tomorrow ;)

**Comment by cognitom** [comment]
@gdub22 I'm a bit new to the server-side Riot, so it's been taking a time to review it. Thank you for waiting.
How about separating the test code from front-end testing? The event handling on browser seems not needed in server-side.

**Comment by gdub22** [comment]
Thanks for reviewing.  I can separate the tests when I get some time.  I kept it in the same file because it was easier to run the same specs on both browser and server.

**Comment by cognitom** [comment]
@gdub22 I'm going to merge this after releasing of v2.3.0 of Riot.js. I'll be back soon. Sorry.

**Comment by gdub22** [comment]
Excellent! I just fixed the conflicts

**Comment by GianlucaGuarini** [comment]
@cognitom I am problem merging the `dev` branch into the master. Can you please fix the conflicts and make a new release 2.3.1? So we can bump a new riot patch release

**Comment by cognitom** [comment]
@GianlucaGuarini can I roll back this merge commit? I need to check this PR more. It seems better to focus to only fix for v2.3.1.

**Comment by GianlucaGuarini** [comment]
@cognitom ok sorry I thought It wasn't that hard

**Comment by cognitom** [comment]
No prob ;-)

**Comment by gdub22** [comment]
@cognitom @GianlucaGuarini Besides resolving any conflicts, what can I do to get this re-merged?

**Comment by GianlucaGuarini** [comment]
I would like to give the lead to @cognitom on this because last time I merged It was a disaster.. :smile:

**Comment by cognitom** [comment]
Oh, sorry. What I have to do is just make a time. I'm still not familiar with server-side riot.

**Comment by GianlucaGuarini** [comment]
I am not even sure it's needed.. I ended up with express and this solution that works pretty well https://github.com/GianlucaGuarini/riot-app-example/blob/master/shared/routes.js

**Comment by gdub22** [comment]
@cognitom @GianlucaGuarini  If this will help you, I can break it up into a few PRs: 
1. Just adding guards so the library doesn't crash on the server.
2. Add or change any APIs so it can be used on the server.
3. Add separate tests with a functioning http server.  

FYI I'm already using this successfully in production.

**Comment by GianlucaGuarini** [comment]
@gdub22 can you please update your pull request making a new one on the current codebase?

**Comment by gdub22** [comment]
@GianlucaGuarini yes, could you sync the dev branch? It looks far behind master

**Comment by GianlucaGuarini** [comment]
I guess @cognitom could help you on that I don't want to destroy everything again like I did last time. Could you collaborate you guys working on this task?

**Comment by GianlucaGuarini** [comment]
@gdub22 btw I have merged the master into the dev branch so you can start patching it

**Pull request merged**
