### PR TITLE
Tag based router

### PR DESCRIPTION
**Pull request by cognitom**
See #79

### CODE REVIEW

**Comment by cognitom** [comment]
I was waiting that `rollup-plugin-node-resolve` supports `modules.root`... but unfortunately there's no activity on it. I'm merging this and will think about it later again.
Let's go!

**Comment by cognitom** [comment]
Hi @GianlucaGuarini, can I release `riot-route@3.1.0`?
This is a new feature, so basically we should `npm version minor`. Or should we stick to `3.0.x` with Riot's version number?

**Comment by GianlucaGuarini** [comment]
`riot-route3.1.0` is fine to me, I probably will release `riot@3.1.0` today as well. Remember to update the [doc](https://github.com/riot/route/tree/master/doc) that I will automatically import on our site

**Comment by cognitom** [comment]
@GianlucaGuarini ok, thanks! Will do.

> I probably will release riot@3.1.0 today as well.

Great!

**Pull request merged**
