### PR TITLE
All route callbacks receive parsed route segments

### LINKED ISSUE #58: Route match action should receive parsed segments
There's very little point in having a route matcher that does not (1) regard the values obtained by `riot.parser.fn1` and (2) inconsistently produces callback function parameters.

Eg:

``` js
riot.route('/fruit/*', function(name) { /* */ })
riot.route('/fruit/apple', function() { /* */ })
riot.route('/fruit/orange', function() { /* */ })
```

Not only is there a `name` parameter JUST for wildcard matching, but this setup requires `fruit` as the bare minimum abstraction.

Expectedly, all route callbacks should plug into the values obtained by `parser.fn1`. In the default scenario, this looks like:

``` js
riot.route('/fruit/*', function(collection, id, action) { /* */ })
riot.route('/fruit/apple', function(collection, id, action){ /* */ })
riot.route('/fruit/orange', function(collection, id, action) { /* */ })
```

Of course, some parameters may still be undefined, but at least you can always expect a set of parameters in the callback.

My second point: We have to have a full set of routes just for `fruit`, and will have to repeat the same set for `cars` and another for `trees`, etc.

This practice only makes sense when you're designating routes for a specific tag or a specific set of tags. This same practice prevent you from having a succinct, global level routes declaration.

The same solution allows for:

``` js
// (1)
riot.route('..', function (collection, id, action) {
  // ..
});

// (2)
riot.route('fruit/apple/..', function (custom, parser, args) {
  // .. long-tail url, read it
});
```

`(1)`: While this isn't a recommended **only** solution, it allows for a nice last resort/"catch-all" which has the power to run its own logic based on params

`(2)`: Dependent on our desired URL structure (and appropriate parser fn), we can allow for deep, complex URLs and handle them all at once without having to declare multiple blocks, repeating boilerplate.

Anyway, Issue getting a bit long here. If this is approved, I have the matching PR ready to be opened. It's a simple 2-line fix

### PR DESCRIPTION
**Pull request by lukeed**
_Every_ route callback is exposed to the full set of route segments, as parsed by the first `parser` function.

More benefits & clarity included in #58 

If accepted, Resolves #58

### CODE REVIEW

**Comment by lukeed** [comment]
@GianlucaGuarini any thoughts on this?

**Comment by GianlucaGuarini** [comment]
@lukeed this is a breaking change and it'd be better introducing it in the version 3.0.0 I will come back to it once riot 3.0.0 will be ready. Thanks for your pull request and hold on for a while ;)

**Comment by lukeed** [comment]
@GianlucaGuarini Sounds good 👍 I've reverted my projects to the current route parsers in the meantime.

The only REAL benefit this PR provides is that it allows for automated route behavior. For example, one could fire off `fruit_index` vs `fruit_show` vs `fruit_edit` events, all based on the `base, id, aciton` parameters.

Then, I think the next logical step would be to include an `always()`-type callback handler to the router. 
Right now, `riot.route(fn)` is more of a catch-all / last resort.

If there was a `riot.route.always(fn)`, users can rely on the self-generating event names, while also triggering custom/specific events based **in addition to** the events from `.always()`

```js
riot.route.always(function (base, id, action) {
  trigger(base + '_' + (action ? action : id ? 'show' : 'index'));
});

riot.route('fruits/apple', function () {
  trigger('custom_apple');
  //=> 'fruits_show' is also being triggered inside .always()
});
```

**Comment by GianlucaGuarini** [comment]
thank you for your PR. I have just released the new Route.js version so I will not accept new PRs on the old version unless they are security patches

**Pull request closed without merging**
