### PR TITLE
The new route rocks!

### PR DESCRIPTION
**Pull request by GianlucaGuarini**
I think we could start merging the new route into the master branch publishing the first beta release on npm

### CODE REVIEW

**Comment by cognitom** [comment]
@tipiirai could you pls check it?

I've made a relatively complex example by our new router.
http://riotjs.com/examples/router-complex/

Open this on Plunker:
http://riotjs.com/examples/plunker/?app=router-complex

Document is here:
https://github.com/riot/route/tree/dev/doc

**Comment by GianlucaGuarini** [comment]
@cognitom I would change your demo removing the hashbang from the url http://run.plnkr.co/plunks/ZDlHLbk7MpDskjAjvBZ4/ I think it shows better the power of the new riot route build on the top of the new html5 history feature.

**Comment by cognitom** [comment]
@GianlucaGuarini :+1: 
Is that ok that it'll fail to reload on GitHub Pages or Plunker?

With `superstatic.json`, we can run this by `ss`:
```json
{
  "routes": {
    "**/*": "index.html"
  }
}
```

**Comment by GianlucaGuarini** [comment]
> Is that ok that it'll fail to reload on GitHub Pages or Plunker?

I hope that who wants to use the html5 history navigation knows what he is doing, so yes.
I wouldn't care too much about page reloads here, normally a devs should handle this via .htaccess

**Comment by cognitom** [comment]
Ok, agreed. Will do ;-)

**Comment by GianlucaGuarini** [comment]
@cognitom thanks, you have done an amazing job. I am gonna merge this

**Comment by GianlucaGuarini** [comment]
I will publish the beta on npm and include the new route in riot dev

**Comment by cognitom** [comment]
:v:

**Comment by tipiirai** [comment]
Looking good! 

Would like to see direct links to Plunker and doc directly from the demo.

**Pull request merged**
