### PR TITLE
added a optional route function on route tag. It is useful to have ro…

### PR DESCRIPTION
**Pull request by dutradda**
…ute tags outside a router tag

### CODE REVIEW

**Comment by cognitom** [comment]
@dutradda thanks for your suggestion!
I'm not sure what's the point..., could you explain more?

**Comment by dutradda** [comment]
@cognitom I have a use case like that:

<my-app>
    <router>
        <my-collection-1/>
        <my-collection-2/>
        <my-collection-3/>
        <my-collection-4/>
        <route path="">
            <my-collection-1-redirect/>
        </route>
        <route path="*">
            <not-found/>
        </route>
    </router>
</my-app>


<my-collection-1>
    <route path="my_collection1" router={this.parent.parent}>
          <p>My Collection 1</p>
    </route>
</my-collection-1>


I can't use subroutes because the "*" path will always resolves together my other subroutes.

If I use:

<my-collection-1>
     <router>
         <route path="my_collection1">
                <p>My Collection 1</p>
         </route>
    </router>
</my-collection-1>

When I put "my_collection1" URL in my browser, the router will resolve both route tags, the "my_collection1" and the "*", because I created two different routers.
so the not-found tag always be mounted.

This PR is for use just one router with routes in different tags.

**Comment by dutradda** [comment]
@cognitom I expressed myself well?

**Comment by GianlucaGuarini** [comment]
thank you for your PR. I have just released the new Route.js version so I will not accept new PRs on the old version unless they are security patches

**Pull request closed without merging**
