### PR TITLE
make start wait for readyState interactive instead complete to avoid …

### PR DESCRIPTION
**Pull request by msveden**
…slow loading resources from blocking the app

Third party scripts, hosted somewhere else, block the router and hence the whole app until  they are loaded. 

The change is in src/index.js, the other changes are made by "npm run build".

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
@msveden could you please avoid changes in the generated files and change only the source code?

**Comment by msveden** [comment]
Sorry I didn't know you didn't keep dist up-to-date with the source. 

I want to be able to refer to my commit in my package.json and use "npm install" and have it up and running just like if it was the official package. 

Is there a way I can do this without changing dist and without modifying the build process for my product?

I can of course just put the change in a different branch. Is that better?

**Comment by GianlucaGuarini** [comment]
@msveden I would make a new clean pull request committing only the source files you have changed and adding `readyState === 'interactive' || readyState === 'complete'` as well

**Comment by msveden** [comment]
Closing this request as it has been replaced by another.

**Pull request closed without merging**
