### PR TITLE
v2.3.0

### PR DESCRIPTION
**Pull request by cognitom**
Pls have a look:

- code: https://github.com/riot/route/blob/v2.3/lib/index.js
- docs: https://github.com/riot/route/blob/v2.3/doc/README.md

### CODE REVIEW

**Comment by cognitom** [comment]
Coverage is 99%. But I don't know how to emulate metakeys on click event on phantomjs...
https://coveralls.io/builds/3497267/source?filename=dist%2Froute.js#L99

Any advice?

**Comment by GianlucaGuarini** [comment]
@cognitom fixed! Now we can merge it, congrats you have done an amazing job

**Comment by GianlucaGuarini** [comment]
@cognitom I have one question, if I create a sub-router is there a way to destroy it? This is not clear from the documentation

**Comment by cognitom** [comment]
@GianlucaGuarini Thank you! Great! :smile: 

> if I create a sub-router is there a way to destroy it?

Yeah, we have a way. I'll add it to the docs:

```javascript
var subRouter = router.create()

router('filter0', function() { /* */ })
subRouter('route-a', function() { /* */ })
subRouter('route-b', function() { /* */ })

subRouter.stop() // stop only route-a and -b
router.stop() // stop everything
```

**Pull request merged**
